Add ADCS ESC15
The-Hacker-Recipes/The-Hacker-Recipes pull request #107
Opened 2024-11-30 09:18 UTC by BlWasp

Hi ! This PR adds the latest ADCS ESC15 attack, regarding arbitrary application policies.
I have also updated the index page of the ADCS section.

2024-12-11 10:35 UTC, ShutdownRepo requested changes
do you mind specifying the CVE now that it's been accepted as such by MS ?
and also mention somewhere that is was a CVE and it's been patched, so up-to-date systems won't be vulnerable to that
https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-49019

2024-12-13 21:56 UTC, BlWasp commented
Hi ! CVE number and note about it added 😄

2024-12-16 07:40 UTC, ShutdownRepo approved these changes

2024-12-16 07:40 UTC, ShutdownRepo commented
woop woop 🤟

2024-12-16 07:40 UTC, merged