Refactor file for align with THR artice structure
The-Hacker-Recipes/The-Hacker-Recipes pull request #78
Opened 2024-09-09 07:01 UTC by Tednoob17

2024-09-12 00:16 UTC, ShutdownRepo requested changes
Thank you for the pull request
There are a few changes I think would be nice to make but after that we should be good to go!
You can make the modifications directly in your current fork, no need to create a new PR from scratch 😉

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +Telnet (teletype network) is a  network protocol used to gain access to virtual terminal in local or in remote systems . He provide  bidirectional text-based communication .
To "a" virtual terminal
"a" missing

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +Telnet (teletype network) is a  network protocol used to gain access to virtual terminal in local or in remote systems . He provide  bidirectional text-based communication .
"He provides" -> "It provides"

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +> The $TARGET_PORT is optional, but the default port is 23
Please add backticks for target port : `$TARGET_PORT`

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +#### CLI tool
Please remove this title

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +
Can you add something like: "From UNIX-like systems, multiple tools can be used to grab the telnet banner of a target."

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +nmap -p  $TARGET_PORT -sVC  --script "*telnet* and safe" $TARGET_IP
Can you add a newline before each comment to separate the tools?

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +
Can you add: "From Windows systems [...]" just like the comment on the unix part?

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +nmap -p  $TARGET_PORT   --script telnet-ntlm-info.nse $TARGET_IP
Please add newlines between the commands, and remove the extra spaces on the last one

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +```
I would move this block in a separate code block right under the unix commands (in the unix tab) with a sentence like "The Metasploit framework" can also be used for the job

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +To connect without a password, you would use the following command:
"You" -> "one"

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +#but not provide any password
Can you add a space after the # ?
Also make it one sentence please : "# provide username, without password"

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +#### Passwordless Authentication
In all titles of this page, please only keep a capital letter on the first word : "Passwordless authentication"

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +Telnet allows users to connect to a server without needing a specific identity by utilizing a passwordless login feature. This method is commonly employed for accessing or downloading public files.
"Telnet allows" -> "Telnet can be configured to allow"

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +#provide a common password
Space after #

2024-09-12 00:16 UTC, ShutdownRepo commented on docs/src/infra/protocols/telnet.md
> +The following commands is typed in msfconsole.
Please remove this sentence, or put it right under the tab name, or else it will be in the preceding tab

2024-09-17 10:35 UTC, Tednoob17 commented
Request Solve

2024-09-27 09:07 UTC, AzeTIIx requested changes
Hey, thanks for your changes I think the content looks good to me. However there is some weird additions to the project depencies

2024-09-27 09:07 UTC, AzeTIIx commented on package-lock.json
Please don't change the project dependencies

2024-09-27 09:07 UTC, AzeTIIx commented on package.json
Please don't change the project dependencies

2024-10-04 05:28 UTC, closed without merging