feat: add api pentest
The-Hacker-Recipes/The-Hacker-Recipes pull request #79
Opened 2024-09-10 18:59 UTC by 0xlildoudou

Hi Team,

I recently did an API pentest and suggest adding a few notes to “The Hackers Recipes”.

Thanks for your work and the redesign of the site.

2024-09-12 08:17 UTC, AzeTIIx commented on docs/src/web/inputs/api.md
> +## Sources
Refactor "Sources" to "Ressources"

2024-09-12 08:21 UTC, AzeTIIx commented on docs/src/web/inputs/api.md
> +https://taget.com/api/users/1 --> 401
"taget" -> "target"

2024-09-12 08:28 UTC, AzeTIIx commented on docs/src/web/inputs/api.md
> +* REST APIs (JSON) : The specificity of a REST API lies in its statelessness, use of standard HTTP methods (GET, POST, PUT, DELETE), and resource-based structure with responses typically formatted in
Add backticks to HTTP methods GET -> `GET`

2024-09-12 13:00 UTC, 0xlildoudou commented
Hi,

I have fix your comment, thanks :)

2024-09-12 13:04 UTC, AzeTIIx commented
One last thing, when I said "refactor taget -> target", I meant it for all the occurences of "taget" 
I didn't make it clear enough, my bad 😅

2024-09-12 13:04 UTC, AzeTIIx requested changes

2024-09-12 13:04 UTC, AzeTIIx commented on docs/src/web/inputs/api.md
>  https://taget.com/api?users=1 --> 200
taget -> target

2024-09-12 13:04 UTC, AzeTIIx commented on docs/src/web/inputs/api.md
>  https://taget.com/api/users?1 --> 200
taget -> target

2024-09-12 13:04 UTC, AzeTIIx commented on docs/src/web/inputs/api.md
>  https://taget.com/api/v1/users/1 --> 200
taget -> target

2024-09-12 14:58 UTC, 0xlildoudou commented
it's fixed
I'm so fucking stupid...

2024-10-23 06:30 UTC, 0xlildoudou commented
Hi,

All is done, can you merge my MR or do you need something else?

2024-10-24 01:10 UTC, AzeTIIx approved these changes

2024-10-24 01:12 UTC, merged