Update webclient.md
The-Hacker-Recipes/The-Hacker-Recipes pull request #81
Opened 2024-09-12 09:52 UTC by Pri3st

Added more ways to enable the webclient service in an unprivileged session.

2024-09-12 09:59 UTC, Pri3st commented
Created a new PR because I had to merge previous commits.

2024-09-25 21:53 UTC, ShutdownRepo requested changes
thank you for the PR, here are some change requests

2024-09-25 21:53 UTC, ShutdownRepo commented on docs/src/ad/movement/mitm-and-coerced-authentications/webclient.md
> +---
this needs to be at the top of the file, along other authors

2024-09-25 21:53 UTC, ShutdownRepo commented on docs/src/ad/movement/mitm-and-coerced-authentications/webclient.md
> +```
can you specify it's `C` code here?

2024-09-25 21:53 UTC, ShutdownRepo commented on docs/src/ad/movement/mitm-and-coerced-authentications/webclient.md
> +```
do you mind putting the code in a collapsible details block?
````md
::: details
```C
...code
```
:::
````

2024-09-25 21:53 UTC, ShutdownRepo commented on docs/src/ad/movement/mitm-and-coerced-authentications/webclient.md
> +```c#
do you mind putting the code in a collapsible details block?
````md
::: details
```C
...code
```
:::
````

2024-09-26 22:46 UTC, Pri3st commented
All changes are made.

2024-10-10 22:56 UTC, ShutdownRepo commented
I simplified the PR by removing the PoCs since you already provided links to them and since they were breaking the tabs (details within tabs don't behave well). If you think we need to include the PoCs, then the best would probably be to offer them as downloadable assets (and I advise to do that in another PR)

2024-10-10 22:56 UTC, ShutdownRepo approved these changes

2024-10-10 22:56 UTC, merged