RPRN with WebClient: /print needed
The-Hacker-Recipes/The-Hacker-Recipes pull request #85
Opened 2024-09-24 14:44 UTC by rtpt-romankarwacik

Abusing WebClient with PrinterBug seems to require a "/print" path. Any counterexamples appreciated.

2024-09-25 21:17 UTC, ShutdownRepo commented
Hmm, do you have any paperwork/blogpost that supports that?
It's very likely that you're right about that 😄

2024-09-26 14:20 UTC, rtpt-romankarwacik commented
I've only seen it used in some blog and forum posts, but it was never addressed by the authors, which I thought was weird. I also do not know why exactly this is needed, it seems to be a specific RPRN thing.

2024-10-10 22:39 UTC, ShutdownRepo commented
Let's merge and wait for a counterexample
@rtpt-romankarwacik do you mind adding your handle at the top of the file in the list of authors?

2024-10-10 22:40 UTC, ShutdownRepo requested changes
Add username at the top of the file in the frontmatter config https://www.thehacker.recipes/contributing#highlighting-contributors

2024-10-11 11:38 UTC, merged