Update pass-the-certificate.md
The-Hacker-Recipes/The-Hacker-Recipes pull request #92
Opened 2024-10-16 13:28 UTC by joker2a

Add Commands to generate a b64 for Rubeus.

2024-10-16 17:17 UTC, AzeTIIx requested changes
Hey, thanks for your contribution! Don't forget to add you as an author in the article frontmatter 😉

2024-10-16 17:17 UTC, AzeTIIx commented on docs/src/ad/movement/kerberos/pass-the-certificate.md
> +> ```bash
Change bash -> powershell

2024-11-21 18:38 UTC, ShutdownRepo approved these changes

2024-11-21 18:39 UTC, ShutdownRepo commented
Thank you for the PR 🎉LGTM

2024-11-21 18:39 UTC, AzeTIIx approved these changes

2024-11-21 18:39 UTC, merged