Updated MECM/SCCM credentials harvesting methodology and tools in SCCM privilege escalation page
The-Hacker-Recipes/The-Hacker-Recipes pull request #98
Opened 2024-11-16 17:31 UTC by q-roland

Hi!

First, thanks for The Hacker Recipes, which is a really cool project.
This PR suggests some changes in the privilege escalation page for MECM/SCCM, more specifically on the credential harvesting part.

We originally wanted to add the fact that a tool now exists to fetch task sequences and collection variables from Unix-based systems (https://github.com/synacktiv/SCCMSecrets/ - for context, I authored the tool), and mention some additional misconfigurations that we have seen in the wild.

We also slightly reorganized the structure of the page to hopefully make it clearer and to properly distinguish between theory and practice.

Do not hesitate if you have any question or remark regarding this PR.
Cheers!

2024-12-11 09:40 UTC, ShutdownRepo commented
Looks good to me but I'm not expert when it comes to SCCM
@BlWasp do you mind taking a look & identify the conflicts with you own PR (#106) ?

2024-12-11 09:49 UTC, BlWasp commented
Hi guys !

Thanks for the PR ! I hadn't seen this PR and I've done something similar on my end 🫠

I'll review this one, and then merge mine if necessary.

2024-12-15 14:46 UTC, q-roland commented
Hi guys, for info I am currently working on implementing HTTPS - and thus client-certificate authentication support in SCCMSecrets.py for both Management Point and Distribution Point interactions. This is a configuration that we regularly encounter during engagements. There were a few twists to implement this, but it should be functional soon.

I may update this PR with info related to secret dumping in HTTPS-enforced environments once the feature is implemented in SCCMSecrets.py - if the current PR is merged in the meantime, I'Il make a new one ;)

Cheers

2024-12-15 18:28 UTC, BlWasp requested changes
Hi all !
@q-roland I have left some comments, can you check them ? 😃 
The PR is globally pretty good. I will verify after the merge, but I think my PR will be useless.

2024-12-15 18:28 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +python3 SCCMSecrets.py files -dp http://mecm.sccm.lab -u 'dave' -H 'F7EB9C06FAFAA23C4BCF22BA6781C1E2' --extensions '.txt,.xml,.ps1,.pfx,.ini,.conf'
On command examples we try to use env variables instead of credentials/FQDN/IP address 😄  Like `$USER`, `$PASSWORD`, `$MECM_IP`, ...
This helps to maintain a certain consistency and continuity between pages, and avoids leaking real credentials or creds from labs such as GOAD 😄

2024-12-15 18:28 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +python3 SCCMSecrets.py files -dp http://mecm.sccm.lab -u 'dave' -p 'dragon' --urls to_download.lst
Same here

2024-12-15 18:28 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +To this end, [SCCMSecrets.py](https://github.com/synacktiv/SCCMSecrets/) can be used. All secret policies associated with the default collections for the newly registered device (including NAAs, Task
When we indicate a tool with its URL like here, we always indicate into brackets its code langage (C#), (Python),... You can look at how it is indicate in the other code examples on the page.
Think about adding (Python) to all the SCCMSecrets references :)

2024-12-15 18:28 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +=== SMB
Hum I'm not sure about the two tabs HTTP/SMB as SCCMSecrets is also able to retrieve the secrets via SMB, if I don't tell a mistake ?
I think it is preferable to keep the usual separation UNIX/Windows, and indicate the dedicated tools into each sections. And maybe, into each tabs devided between HTTP and SMB.

2024-12-15 18:28 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +##### Step 3: coerce authentication
The Step 4 is still marked `4. Obtain an SQL console` bellow. Can you change it to `##### Step 4: Obtain an SQL console` ?

2024-12-17 16:17 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +> This concretely means that an attacker that has a machine account or that is able to relay one can register an approved device and dump secret policies. Also, note that it is possible to **misconfi
You're right, it would be better to be explicit - I'm adding a clarification :)

2024-12-17 16:18 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +Some policies may contain sensitive data and are tagged as **secret policies**. Only registered SCCM devices in the **approved** state may request them. By default in SCCM, two device registration en
A computer account is actually only needed for the authenticated registration endpoint - when using the unauthenticated endpoint, there is no need to provide any kind of credentials to register a new device. As explained in the extract, this second case may not be very useful because the registered device is not approved by default. But this behaviour may be exploited if anonymous device approval is enabled (the misconfiguration highlighted just below). I would prefer keeping the current formulation to be explicit about how the misconfiguration mentioned below arises, if that's ok with you

2024-12-17 16:18 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +Three kind of secret policies can contain secrets and/or account credentials:
Agreed, I reworded this sentence - these are rather three different kinds of policies that are flagged as "secret" by SCCM

2024-12-17 16:19 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +> This concretely means that an attacker with any domain account can fetch Distribution Point resources. In addition, it is possible to **misconfigure** SCCM Distribution Points to allow anonymous ac
Indeed, I added a clarification. I also added the fact that SMB is always authenticated here in addition to the Practice section

2024-12-17 16:20 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +The [sccmhunter](https://github.com/garrettfoster13/sccmhunter) tool also implements `sccmwtf`, but with the same limitations.
Agreed, I put the sccmhunter commands back in this section

2024-12-17 16:20 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +Finally, it should be mentioned that the Network Access Accounts (NAAs) credentials are stored on the disk of SCCM clients, encrypted with DPAPI. Interestingly enough, even after deleting or changing
That's absolutely correct, thanks for the info. I added this point.

2024-12-17 16:21 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +SystemDPAPIdump.py -creds -sccm $DOMAIN/$USER:$PASSWORD@target.$DOMAIN
Agreed, I added the command

2024-12-17 16:21 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +# Native Powershell
Indeed, thanks, I'm adding this

2024-12-17 16:22 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +Note that if anonymous access was configured on a Distribution Point, only the HTTP protocol can be used to download files without any credentials.
See my comment above, I followed your recommendation and mentioned this point in the Theory section

2024-12-17 16:23 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +python3 SCCMSecrets.py files -dp http://mecm.sccm.lab -u 'dave' -H 'F7EB9C06FAFAA23C4BCF22BA6781C1E2' --extensions '.txt,.xml,.ps1,.pfx,.ini,.conf'
Yeah env variables are cleaner, I should have replaced creds/FQDN/IPs in all the commands :)

2024-12-17 16:23 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +To this end, [SCCMSecrets.py](https://github.com/synacktiv/SCCMSecrets/) can be used. All secret policies associated with the default collections for the newly registered device (including NAAs, Task
Indeed, I've added this format to the various tool references on the page

2024-12-17 16:24 UTC, q-roland commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +=== SMB
SCCMSecrets only performs secrets retrieval via HTTP for the moment, I've not implemented the SMB protocol as cmloot.py does this pretty well :) but I followed your suggestion and put back the usual Unix/Windows separation for coherence, and added HTTP/SMB subsection in the tabs

2024-12-17 16:38 UTC, q-roland commented
Hey @BlWasp, thanks for the fixes and suggestions, I ended up implementing (almost 😄) all of them, you can see the details in my comments above.

I also added a part regarding the SCCM configuration enforcing HTTPS and client certificate authentication as promised in my last comment.

Don't hesitate if there are additional changes that you would like implemented in the PR.

Thanks again

2024-12-18 11:10 UTC, BlWasp approved these changes
The changes look good for me, thanks again for the PR @q-roland  !
@ShutdownRepo I think this one is ready for merging.

2024-12-18 11:10 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +SystemDPAPIdump.py -creds -sccm $DOMAIN/$USER:$PASSWORD@target.$DOMAIN
Ok, that's good for me.

2024-12-18 11:10 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +# Native Powershell
Good for me.

2024-12-18 11:12 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +=== SMB
Oh ok, sorry for the mistake ! By reading the article on the Synacktiv's blog I thought it was possible to parse the SMB share as well

2024-12-18 11:17 UTC, BlWasp commented on docs/src/ad/movement/sccm-mecm/privilege-escalation.md
> +Some policies may contain sensitive data and are tagged as **secret policies**. Only registered SCCM devices in the **approved** state may request them. By default in SCCM, two device registration en
Yeah I'm totally ok with this. My point was just to indicate that, in a normal SCCM workflow, sysadmins can manually validate device enrolment through the console.
But I agree that it perhaps unnecessarily burdens the explanations for nothing. Maybe it's better to leave it like that

2025-02-15 12:39 UTC, ShutdownRepo commented
Thank you @q-roland for the contribution, and @BlWasp for the review!

2025-02-15 12:42 UTC, ShutdownRepo approved these changes

2025-02-15 12:42 UTC, merged